steps:
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y libjpeg-dev zlib1g-dev build-essential
        pip install -r requirements.txt pytest pytest-mock
        python -m spacy download en_core_web_sm
        pytest tests/
